name: Build
on: [push, pull_request]

jobs:
  build:
    # matrix for both release and debug builds
    strategy:
      matrix:
        configuration: [Release, Debug]

    runs-on: windows-2019 # need older VM for .NETFramwork v4.0
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1 # Need msbuild (not dotnet) for .net framework
      # TODO, build both release and debug, but only publish release
      - name: Build (${{ matrix.configuration }} flavor)
        run: msbuild /p:Configuration=${{ matrix.configuration }}
      - name: Publish Github release
        uses: softprops/action-gh-release@v1
        if: ${{ matrix.configuration == 'Release' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        with:
          name: ${{ github.event.repository.name }} v1.0.${{ github.run_number }}
          files: |
            merge-solutions\bin\Release\*.exe
            merge-solutions\bin\Release\*.pdb
permissions:
  contents: write # for create-release
